### ISSUE TITLE
Anisotropy fail on Fiji 1.52g

### ISSUE THREAD

**Issue by kld123509945** [bonej-org/BoneJ2#141]
Hi all,
I just create a sample binary image stack, and the Anisotropy module failed.
The steps are:
1. import a image stack into Fiji
2. Click on BoneJ - Anisotropy
3. click the Recommended minimum, which sets 2000 directions, 100 Lines per dimension and 1 Sampling increment.
4. See error in Log and nothing was calculated.
Please see:
`http://imglf5.nosdn0.126.net/img/M3B0VGdGQVdIRGlGMHFHME9zQ1EraDJkYXlGRWVOeUphekpqQmo1VXM3TXYvcUtZcVd3MGJRPT0.png?imageView&thumbnail=2801y1551&type=png&quality=96&stripmeta=0`

Log:

[Fri Sep 28 23:12:55 BST 2018] [ERROR] [] Module threw error
java.lang.NoClassDefFoundError: net/imagej/ops/stats/regression/leastSquares/Quadric
	at org.bonej.wrapperPlugins.AnisotropyWrapper.matchOps(AnisotropyWrapper.java:271)
	at org.bonej.wrapperPlugins.AnisotropyWrapper.run(AnisotropyWrapper.java:193)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.imagej.ops.stats.regression.leastSquares.Quadric
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
[Fri Sep 28 23:14:15 BST 2018] [ERROR] [] Module threw error
java.lang.NoClassDefFoundError: net/imagej/ops/stats/regression/leastSquares/Quadric
	at org.bonej.wrapperPlugins.AnisotropyWrapper.matchOps(AnisotropyWrapper.java:271)
	at org.bonej.wrapperPlugins.AnisotropyWrapper.run(AnisotropyWrapper.java:193)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[Fri Sep 28 23:19:23 BST 2018] [ERROR] [] Module threw error
java.lang.NoClassDefFoundError: net/imagej/ops/stats/regression/leastSquares/Quadric
	at org.bonej.wrapperPlugins.AnisotropyWrapper.matchOps(AnisotropyWrapper.java:271)
	at org.bonej.wrapperPlugins.AnisotropyWrapper.run(AnisotropyWrapper.java:193)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[Fri Sep 28 23:25:56 BST 2018] [ERROR] [] Module threw error
java.lang.NoClassDefFoundError: net/imagej/ops/stats/regression/leastSquares/Quadric
	at org.bonej.wrapperPlugins.AnisotropyWrapper.matchOps(AnisotropyWrapper.java:271)
	at org.bonej.wrapperPlugins.AnisotropyWrapper.run(AnisotropyWrapper.java:193)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[Fri Sep 28 23:26:29 BST 2018] [ERROR] [] Module threw error
java.lang.NoClassDefFoundError: net/imagej/ops/stats/regression/leastSquares/Quadric
	at org.bonej.wrapperPlugins.AnisotropyWrapper.matchOps(AnisotropyWrapper.java:271)
	at org.bonej.wrapperPlugins.AnisotropyWrapper.run(AnisotropyWrapper.java:193)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Environment**
 - Win10
 - Java version 1.8.0_172 (64-bit)
 - BoneJ is updated through Fiji update.

**Comment by ctrueden** [comment]
It looks like the latest BoneJ2 build was uploaded to the BoneJ update site, but the corresponding latest ImageJ Ops release that BoneJ2 depends on has not yet been uploaded to the core update site.

This is partially my fault for being slow in pushing out the new ImageJ Ops release. But it is also a problem with how BoneJ is currently being deployed—there is nothing safeguarding against such skews.

**Comment by kld123509945** [comment]
Thanks for your help! So what could I do now? e.g. Change my Fiji version? Otherwise, considering the  Anisotropy module, could you upload a currently available version of both Fiji and BoneJ? Many thanks!

**Comment by rimadoma** [comment]
Hi @kld123509945 I added the missing dependency to the update site, and I tested it's working now. Try running _Help > Update..._ again, and it should show `imagej-ops:0.42.0` available from the BoneJ update site. If not, then disable the update site, let Fiji uninstall everything, restart Fiji, and then enable the update site again. Apologies for the bother.

@ctrueden So the lesson here is that if we depend on newer artefacts then declared in the `pom-scijava` BOM, we need to have them "shadowed" on the BoneJ update site?

**Comment by kld123509945** [comment]
@rimadoma Thanks so much for your help! The imagej-ops:0.42.0 didn't show, so I do the 4 steps as you told me. This method works! Shown as:

> http://imglf5.nosdn0.126.net/img/M3B0VGdGQVdIRGowRzJQeGlnYWlqOURnMFZiR0pqd0cyNjR0ZnVlb0pkSVIwRVVGdlFyV3VnPT0.png?imageView&thumbnail=1680x0&quality=96&stripmeta=0

BTW, may I ask that how could I save the results in the BoneJ results window? e.g. save it as a .csv or .txt in the hard disk? I cannot see any button or command to save the result like:

> http://imglf6.nosdn0.126.net/img/M3B0VGdGQVdIRGowRzJQeGlnYWlqL0VoWjhNZkZ0eWU1T05UTlQ0SjJoNVlrbjEwR0ZQWERBPT0.png?imageView&thumbnail=2264y726&type=png&quality=96&stripmeta=0

Many thanks!

**Comment by rimadoma** [comment]
@kld123509945  If you click to select a row, you can use the common hot keys for copy-pasting, i.e. _Ctrl + C_ for copying, and then _Ctrl + V_ to paste it, e.g. to your favourite text editor. You can select multiple rows by holding down _Ctrl_, or key _Ctrl + A_ to select them all.

**Comment by ctrueden** [comment]
> @ctrueden So the lesson here is that if we depend on newer artefacts then declared in the pom-scijava BOM, we need to have them "shadowed" on the BoneJ update site?

Unfortunately, the lesson is more complicated than that. Yes, if you depend on a newer imagej-ops, and you want to release your new BoneJ with that dependency _before_ the core update sites are shipping the new imagej-ops, then yes, you need to upload imagej-ops to your site as well.

_However_, you then have the responsibility of _removing_ that version of imagej-ops once it (or a newer version) gets uploaded to the core update site. Otherwise, your shadowed now-older version will continue to take precedence, and break core ImageJ features that might depend on the newer imagej-ops.

Best practice here is not to shadow imagej-ops at all, and instead push for the core update site to get the newest versions deployed as soon as possible. I have been slow about this, but this week I am working on deploying a new version of the whole Fiji software stack. I will try to remember to ping you once the latest imagej-ops has been deployed, so that we can mark the version on BoneJ as obsolete.
