### ISSUE TITLE
Particle analyser failed for some particular images

### ISSUE THREAD

**Issue by kld123509945** [bonej-org/BoneJ2#146]
When I ran the Particle analyser(3D), I notice that the plug-in failed to go on, and a bug window jump out as follows:

(Fiji Is Just) ImageJ 2.0.0-rc-68/1.52g; Java 1.8.0_172 [64-bit]; Windows 10 10.0; 783MB of 15251MB (5%)
 
java.lang.ArrayIndexOutOfBoundsException: 1402
	at org.bonej.plugins.ParticleCounter.mergeDuplicates(ParticleCounter.java:2137)
	at org.bonej.plugins.ParticleCounter.joinMappedStructures(ParticleCounter.java:2043)
	at org.bonej.plugins.ParticleCounter.getParticles(ParticleCounter.java:1744)
	at org.bonej.plugins.ParticleCounter.getParticles(ParticleCounter.java:1668)
	at org.bonej.plugins.ParticleCounter.run(ParticleCounter.java:258)
	at ij.IJ.runUserPlugIn(IJ.java:228)
	at ij.IJ.runPlugIn(IJ.java:192)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)

I'm using the newest version of BoneJ as I update it in the Help-update.

I have upload the CT image stacks for your test. As the former 202 slices works well in Particle analyser(3D), when I start add the No. 203 onto the stack, the Particle analyser(3D) corrupted.  
https://1drv.ms/f/s!At8hOBAhBGnMiAeZLoX0JtBNAOIo
Please help me to test it. Many thanks!

**Comment by mdoube** [comment]
I can confirm.

When I import all 203 slices and run Particle Analyser I get the same AIOOB exception. When I delete the 203rd slice and run Particle Analyser again, it works fine. When I import just the first 202 images it also works fine. If I delete the second to last image from the 203 slice stack making a 202-slice stack missing cb0201 but including cb0202, I get the exception again. So I think there is something wrong with the image slice cb0202 that is breaking the code. It is possible to run Particle Analyser on cb0202 as a single slice (works fine), or as the last slice of a substack made from the last 4 slices of the series.

This bug is not present in the ImageJ1 version of the code, and it hasn't changed much during @rimadoma's porting effort. I'll take a look. Thanks for the test data @kld123509945 .

**Comment by mdoube** [comment]
This bug was introduced in 10fc038
