### ISSUE TITLE
Test error after updating from `net.imagej.Table` to `org.scijava.Table`

### ISSUE THREAD

**Issue by mdoube** [bonej-org/BoneJ2#161]
**Describe the bug**
Build fails complaining about table cleaner test. I can't find any stale references to `net.imagej.table` in BoneJ2.

**To Reproduce**
1. Check out 864902da
2. Run `mvn test -PallTests`
3. See error:

```
[ERROR] Module threw error
java.lang.NoSuchMethodError: org.bonej.utilities.SharedTable.getTable()Lnet/imagej/table/Table;
	at org.bonej.wrapperPlugins.tableTools.SharedTableCleaner.run(SharedTableCleaner.java:51)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
**Additional context**
I see this in `SharedTable.getTable()`:
```
	public static Table<DefaultColumn<Double>, Double> getTable() {
		if (publicCopy == null) {
			publicCopy = createTable();
		}
		else {
			// Calling publicCopy.clear() would be simpler, but it breaks the tests of
			// the class. However, the tests fail only when run together, individually
			// they pass.
			publicCopy.setRowCount(0);
			publicCopy.setColumnCount(0);
		}
		table.forEach(publicCopy::add);
		// Just calling publicCopy::add is not enough to update size info
		// (ThicknessWrapperTests fail)
		publicCopy.setRowCount(table.getRowCount());
		publicCopy.setColumnCount(table.getColumnCount());
		for (int i = 0; i < table.getRowCount(); i++) {
			publicCopy.setRowHeader(i, table.getRowHeader(i));
		}
		return publicCopy;
	}
```

**Comment by mdoube** [comment]
Clearing out my `.m2/repository` (deleting everything) and starting again (`mvn clean package`) leads to different errors:
```
[ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 8.185 s <<< FAILURE! - in org.bonej.wrapperPlugins.AnisotropyWrapperTest
[ERROR] testAnisotropicCalibrationWithinToleranceDoesNotShowWarningDialog(org.bonej.wrapperPlugins.AnisotropyWrapperTest)  Time elapsed: 0.599 s  <<< FAILURE!
```
But running `mvn test -PallTests` again clears the tests - all report SUCCESS. I'll close this issue, but would appreciate pointers about what is going on here.
