### ISSUE TITLE
Fractal Dimension fails with AIOOB exception on large data

### ISSUE THREAD

**Issue by mdoube** [bonej-org/BoneJ2#163]
**Describe the bug**

**To Reproduce**
1. Make a new image, 1360 x 1360 x 2293 pixels, black, 8-bit
2. Run Fractal Dimension, Automatic settings

**Expected behavior**
Fractal dimension finishes and writes results to shared results table

**Environment**
 - OS: Ubuntu, Mac

**Additional context**
```
[Mon Dec 17 13:13:20 HKT 2018] [ERROR] [] Module threw exception
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: -2068372576
	at net.imagej.ops.thread.chunker.DefaultChunker.run(DefaultChunker.java:103)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at net.imagej.ops.OpEnvironment.run(OpEnvironment.java:950)
	at net.imagej.ops.OpEnvironment.run(OpEnvironment.java:157)
	at net.imagej.ops.map.MapUnaryComputers$IIToIIParallel.compute(MapUnaryComputers.java:101)
	at net.imagej.ops.map.MapUnaryComputers$IIToIIParallel.compute(MapUnaryComputers.java:87)
	at net.imagej.ops.special.chain.UHCFViaUC.compute(UHCFViaUC.java:65)
	at net.imagej.ops.special.hybrid.UnaryHybridCF.calculate(UnaryHybridCF.java:61)
	at net.imagej.ops.special.hybrid.UnaryHybridCF.run(UnaryHybridCF.java:71)
	at net.imagej.ops.special.hybrid.UnaryHybridCF.run(UnaryHybridCF.java:97)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at net.imagej.ops.OpEnvironment.run(OpEnvironment.java:950)
	at net.imagej.ops.OpEnvironment.run(OpEnvironment.java:157)
	at net.imagej.ops.convert.ConvertNamespace.bit(ConvertNamespace.java:132)
	at org.bonej.wrapperPlugins.wrapperUtils.Common.toBitTypeImgPlus(Common.java:80)
	at org.bonej.wrapperPlugins.FractalDimensionWrapper.run(FractalDimensionWrapper.java:172)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: -2068372576
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.ops.thread.chunker.DefaultChunker.run(DefaultChunker.java:97)
	... 24 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: -2068372576
	at net.imglib2.img.basictypeaccess.array.AbstractByteArray.getValue(AbstractByteArray.java:61)
	at net.imglib2.type.numeric.integer.GenericByteType.getByte(GenericByteType.java:127)
	at net.imglib2.type.numeric.integer.UnsignedByteType.get(UnsignedByteType.java:151)
	at net.imglib2.type.numeric.integer.UnsignedByteType.getIntegerLong(UnsignedByteType.java:168)
	at net.imagej.ops.convert.ConvertTypes$IntegerToBit.compute(ConvertTypes.java:102)
	at net.imagej.ops.convert.ConvertTypes$IntegerToBit.compute(ConvertTypes.java:89)
	at net.imagej.ops.map.Maps.map(Maps.java:297)
	at net.imagej.ops.map.MapUnaryComputers$IIToIIParallel$1.execute(MapUnaryComputers.java:106)
	at net.imagej.ops.thread.chunker.DefaultChunker$1.run(DefaultChunker.java:77)
	at org.scijava.thread.DefaultThreadService$2.run(DefaultThreadService.java:221)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	... 4 more
```
Reported by Larry Anovitz [on the mailing list](http://imagej.1557.x6.nabble.com/bonej-java-problem-td5021548.html)

**Comment by mdoube** [comment]
This is the offending code in ` org.bonej.wrapperPlugins.wrapperUtils.Common.toBitTypeImgPlus()`

```final Img<BitType> convertedImg = ops.convert().bit(imgPlus.getImg());```

**Comment by mdoube** [comment]
https://github.com/bonej-org/BoneJ2/blob/864902da53a34adb3b5072ab58ae9e5d7310f35c/Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/wrapperUtils/Common.java#L80

**Comment by LMAnovitz** [comment]
a 1206 x 1206 x 2293 image also fails with the same problem

**Comment by LMAnovitz** [comment]
1024 x 1024 x 2293 also fails (and loses part of the data)

**Comment by mdoube** [comment]
Thanks @LMAnovitz could you try with fewer slices? It may help us to understand which of _x_, _y_, and/or _z_ dimensions are important. Is it an absolute number of pixels in the image, or a single dimension getting too big, or an unhandled combination of values?

**Comment by LMAnovitz** [comment]
Shall do – will try 2048 slices later today
--Larry

**Comment by ctrueden** [comment]
I think @bnorthan has a tentative fix for this bug; see imagej/imagej-ops#589. Still in code review.

**Comment by rimadoma** [comment]
I agree with @ctrueden. The fix should also solve issue #106. Even so, it might still be worth using a ConvertService in 'Common. convertToBitImgPlus' instead of explicitly calling a specific conversion op though. 3
