### ISSUE TITLE
Update scijava version to 30.0.0

### ISSUE THREAD

**Issue by mdoube** [bonej-org/BoneJ2#282]
**Describe the bug**
BoneJ is using scijava v. 29.2.1 but 30.0.0 is current

The updater script is complaining...

**Comment by mdoube** [comment]
Tests fail, IIRC this is likely to be in the way the test data maker generates the data or the way the tests check the dimensions. In the past this was resolved only by removing tests.
```
[ERROR] Tests run: 18, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 0.978 s <<< FAILURE! - in org.bonej.wrapperPlugins.AnalyseSkeletonWrapperTest
[ERROR] testIntensityImageChannelsCancelPlugin(org.bonej.wrapperPlugins.AnalyseSkeletonWrapperTest)  Time elapsed: 0.043 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[The intensity image can't have a channel dimension]> but was:<[An error occurred while opening the image]>
	at org.bonej.wrapperPlugins.AnalyseSkeletonWrapperTest.testIntensityImageChannelsCancelPlugin(AnalyseSkeletonWrapperTest.java:188)

[ERROR] testIntensityImageFramesCancelPlugin(org.bonej.wrapperPlugins.AnalyseSkeletonWrapperTest)  Time elapsed: 0.024 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[The intensity image can't have a time dimension]> but was:<[An error occurred while opening the image]>
	at org.bonej.wrapperPlugins.AnalyseSkeletonWrapperTest.testIntensityImageFramesCancelPlugin(AnalyseSkeletonWrapperTest.java:206)

[ERROR] testIntensityImageMismatchingDimensionsCancelPlugin(org.bonej.wrapperPlugins.AnalyseSkeletonWrapperTest)  Time elapsed: 0.035 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[The intensity image should match the dimensionality of the input] image> but was:<[An error occurred while opening the] image>
	at org.bonej.wrapperPlugins.AnalyseSkeletonWrapperTest.testIntensityImageMismatchingDimensionsCancelPlugin(AnalyseSkeletonWrapperTest.java:226)

[ERROR] testNot8BitIntensityImageCancelsPlugin(org.bonej.wrapperPlugins.AnalyseSkeletonWrapperTest)  Time elapsed: 0.018 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[The intensity image needs to be 8-bit greyscal]e> but was:<[An error occurred while opening the imag]e>
	at org.bonej.wrapperPlugins.AnalyseSkeletonWrapperTest.testNot8BitIntensityImageCancelsPlugin(AnalyseSkeletonWrapperTest.java:293)

```

**Comment by alessandrofelder** [comment]
Agreed, it's the way the test data is created in the tests that causes these failures, similar to #275. One way forward that I'd be happy with would be to document these failures in #275 or a separate issue, and remove the tests for now?

**Comment by mdoube** [comment]
Scijava was updated in #311 to 31.1.0
