### ISSUE TITLE
mvn test -P allTests fails with errors about NoClassDefFound

### ISSUE THREAD

**Issue by mdoube** [bonej-org/BoneJ2#293]
**Describe the bug**
Maven complains about failing / missing tests with `NoClassDefFound`

**To Reproduce**
1. check out https://github.com/bonej-org/BoneJ2/tree/aligned-box
2. run `mvn clean package; mvn test -P allTests`

**Expected behavior**
Maven doesn't complain very much

**Additional context**
Relevant bits of the console output:
```
[ERROR] Tests run: 13, Failures: 0, Errors: 13, Skipped: 0, Time elapsed: 1.124 s <<< FAILURE! - in org.bonej.utilities.ElementUtilTest
[ERROR] testCalibratedSpatialElementSizeThrowsIAEIfNoSpatialAxes(org.bonej.utilities.ElementUtilTest)  Time elapsed: 1.018 s  <<< ERROR!
java.lang.ExceptionInInitializerError
	at org.bonej.utilities.ElementUtilTest.<clinit>(ElementUtilTest.java:85)

[ERROR] testCalibratedSpatialElementSizeNoUnits(org.bonej.utilities.ElementUtilTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.ElementUtilTest

[ERROR] testCalibratedSpatialElementSizeUnitsInconvertible(org.bonej.utilities.ElementUtilTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.ElementUtilTest

[ERROR] testCalibratedSpatialElementSize(org.bonej.utilities.ElementUtilTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.ElementUtilTest

[ERROR] testCalibratedSpatialElementSizeThrowsNPEIfNullUnitService(org.bonej.utilities.ElementUtilTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.ElementUtilTest

[ERROR] testIsBinaryReturnsFalseForMultiValue(org.bonej.utilities.ElementUtilTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.ElementUtilTest

[ERROR] testIsBinary(org.bonej.utilities.ElementUtilTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.ElementUtilTest

[ERROR] testCalibratedSpatialElementSizeNonLinearAxis(org.bonej.utilities.ElementUtilTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.ElementUtilTest

[ERROR] testIsBinaryReturnsTrueForMonochrome(org.bonej.utilities.ElementUtilTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.ElementUtilTest

[ERROR] testCalibratedSpatialElementSizeThrowsNPIfENullSpace(org.bonej.utilities.ElementUtilTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.ElementUtilTest

[ERROR] testIsBinaryBooleanTypeAssignable(org.bonej.utilities.ElementUtilTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.ElementUtilTest

[ERROR] testIsBinaryThrowsNPEIfIntervalNull(org.bonej.utilities.ElementUtilTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.ElementUtilTest

[ERROR] org.bonej.utilities.ElementUtilTest  Time elapsed: 0.004 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.ElementUtilTest
```
```
[ERROR] Tests run: 21, Failures: 0, Errors: 21, Skipped: 0, Time elapsed: 0.064 s <<< FAILURE! - in org.bonej.utilities.AxisUtilsTest
[ERROR] isSpatialCalibrationsIsotropic(org.bonej.utilities.AxisUtilsTest)  Time elapsed: 0.061 s  <<< ERROR!
java.lang.ExceptionInInitializerError
	at org.bonej.utilities.AxisUtilsTest.<clinit>(AxisUtilsTest.java:84)

[ERROR] testHasTimeDimensions(org.bonej.utilities.AxisUtilsTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.AxisUtilsTest

[ERROR] testHasChannelDimensionsThrowsNPEIfSpaceNull(org.bonej.utilities.AxisUtilsTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.AxisUtilsTest

[ERROR] isSpatialCalibrationsIsotropicAnisotropicBeyondTolerance(org.bonej.utilities.AxisUtilsTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.AxisUtilsTest

[ERROR] testHasChannelDimensions(org.bonej.utilities.AxisUtilsTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.AxisUtilsTest

[ERROR] testGetSpatialUnitThrowsNPEIfUnitServiceNull(org.bonej.utilities.AxisUtilsTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.AxisUtilsTest

[ERROR] testGetSpatialUnit(org.bonej.utilities.AxisUtilsTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.AxisUtilsTest

[ERROR] testGetSpatialUnitThrowsNPEIfSpaceNull(org.bonej.utilities.AxisUtilsTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.AxisUtilsTest

[ERROR] isSpatialCalibrationsIsotropicThrowsIAENegativeTolerance(org.bonej.utilities.AxisUtilsTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.AxisUtilsTest

[ERROR] isSpatialCalibrationsIsotropicThrowsIAENanTolerance(org.bonej.utilities.AxisUtilsTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.AxisUtilsTest

[ERROR] isSpatialCalibrationsIsotropicThrowsIAEInconvertibleUnits(org.bonej.utilities.AxisUtilsTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.AxisUtilsTest

[ERROR] testGetSpatialUnitInconvertibleUnits(org.bonej.utilities.AxisUtilsTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.AxisUtilsTest

[ERROR] testGetSpatialUnitAllAxesUncalibrated(org.bonej.utilities.AxisUtilsTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.AxisUtilsTest

[ERROR] testCountSpatialDimensionsThrowsNPEIfNullSpace(org.bonej.utilities.AxisUtilsTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.AxisUtilsTest

[ERROR] isSpatialCalibrationsIsotropicDifferentUnits(org.bonej.utilities.AxisUtilsTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.AxisUtilsTest

[ERROR] testHasSpatialDimensionsThrowsNPEIfSpaceNull(org.bonej.utilities.AxisUtilsTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.AxisUtilsTest

[ERROR] testHasSpatialDimensions(org.bonej.utilities.AxisUtilsTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.AxisUtilsTest

[ERROR] testHasTimeDimensionsThrowsNPEIfSpaceNull(org.bonej.utilities.AxisUtilsTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.AxisUtilsTest

[ERROR] isSpatialCalibrationsIsotropicAnisotropicWithinTolerance(org.bonej.utilities.AxisUtilsTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.AxisUtilsTest

[ERROR] testGetSpatialUnitThrowsIAEIfNoSpatialAxes(org.bonej.utilities.AxisUtilsTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.AxisUtilsTest

[ERROR] org.bonej.utilities.AxisUtilsTest  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bonej.utilities.AxisUtilsTest
```

```
[ERROR] Errors: 
[ERROR]   AxisUtilsTest.isSpatialCalibrationsIsotropic » ExceptionInInitializer
[ERROR]   AxisUtilsTest.isSpatialCalibrationsIsotropicAnisotropicBeyondTolerance » NoClassDefFound
[ERROR]   AxisUtilsTest.isSpatialCalibrationsIsotropicAnisotropicWithinTolerance » NoClassDefFound
[ERROR]   AxisUtilsTest.isSpatialCalibrationsIsotropicDifferentUnits » NoClassDefFound C...
[ERROR]   AxisUtilsTest.isSpatialCalibrationsIsotropicThrowsIAEInconvertibleUnits » NoClassDefFound
[ERROR]   AxisUtilsTest.isSpatialCalibrationsIsotropicThrowsIAENanTolerance » NoClassDefFound
[ERROR]   AxisUtilsTest.isSpatialCalibrationsIsotropicThrowsIAENegativeTolerance » NoClassDefFound
[ERROR]   AxisUtilsTest.org.bonej.utilities.AxisUtilsTest » NoClassDefFound Could not in...
[ERROR]   AxisUtilsTest.testCountSpatialDimensionsThrowsNPEIfNullSpace » NoClassDefFound
[ERROR]   AxisUtilsTest.testGetSpatialUnit » NoClassDefFound Could not initialize class ...
[ERROR]   AxisUtilsTest.testGetSpatialUnitAllAxesUncalibrated » NoClassDefFound Could no...
[ERROR]   AxisUtilsTest.testGetSpatialUnitInconvertibleUnits » NoClassDefFound Could not...
[ERROR]   AxisUtilsTest.testGetSpatialUnitThrowsIAEIfNoSpatialAxes » NoClassDefFound Cou...
[ERROR]   AxisUtilsTest.testGetSpatialUnitThrowsNPEIfSpaceNull » NoClassDefFound Could n...
[ERROR]   AxisUtilsTest.testGetSpatialUnitThrowsNPEIfUnitServiceNull » NoClassDefFound C...
[ERROR]   AxisUtilsTest.testHasChannelDimensions » NoClassDefFound Could not initialize ...
[ERROR]   AxisUtilsTest.testHasChannelDimensionsThrowsNPEIfSpaceNull » NoClassDefFound C...
[ERROR]   AxisUtilsTest.testHasSpatialDimensions » NoClassDefFound Could not initialize ...
[ERROR]   AxisUtilsTest.testHasSpatialDimensionsThrowsNPEIfSpaceNull » NoClassDefFound C...
[ERROR]   AxisUtilsTest.testHasTimeDimensions » NoClassDefFound Could not initialize cla...
[ERROR]   AxisUtilsTest.testHasTimeDimensionsThrowsNPEIfSpaceNull » NoClassDefFound Coul...
[ERROR]   ElementUtilTest.org.bonej.utilities.ElementUtilTest » NoClassDefFound Could no...
[ERROR]   ElementUtilTest.testCalibratedSpatialElementSize » NoClassDefFound Could not i...
[ERROR]   ElementUtilTest.testCalibratedSpatialElementSizeNoUnits » NoClassDefFound Coul...
[ERROR]   ElementUtilTest.testCalibratedSpatialElementSizeNonLinearAxis » NoClassDefFound
[ERROR]   ElementUtilTest.testCalibratedSpatialElementSizeThrowsIAEIfNoSpatialAxes » ExceptionInInitializer
[ERROR]   ElementUtilTest.testCalibratedSpatialElementSizeThrowsNPEIfNullUnitService » NoClassDefFound
[ERROR]   ElementUtilTest.testCalibratedSpatialElementSizeThrowsNPIfENullSpace » NoClassDefFound
[ERROR]   ElementUtilTest.testCalibratedSpatialElementSizeUnitsInconvertible » NoClassDefFound
[ERROR]   ElementUtilTest.testIsBinary » NoClassDefFound Could not initialize class org....
[ERROR]   ElementUtilTest.testIsBinaryBooleanTypeAssignable » NoClassDefFound Could not ...
[ERROR]   ElementUtilTest.testIsBinaryReturnsFalseForMultiValue » NoClassDefFound Could ...
[ERROR]   ElementUtilTest.testIsBinaryReturnsTrueForMonochrome » NoClassDefFound Could n...
[ERROR]   ElementUtilTest.testIsBinaryThrowsNPEIfIntervalNull » NoClassDefFound Could no...
[INFO] 
[ERROR] Tests run: 66, Failures: 0, Errors: 34, Skipped: 0
```

**Comment by mdoube** [comment]
Having trouble reproducing this. Tests pass (except the known one about Fractal Dimension) on the workstation where they failed yesterday. On laptop a new error is thrown:
 ```
[ERROR] Failures: 
[ERROR]   AnisotropyWrapperTest.testNonBinaryImageCancelsWrapper:182 
userInterface.dialogPrompt(
    <any string>,
    <any string>,
    <any>,
    <any>
);
Wanted 1 time:
-> at org.bonej.wrapperPlugins.CommonWrapperTests.testNonBinaryImageCancelsPlugin(CommonWrapperTests.java:181)
But was 2 times:
-> at org.scijava.ui.DefaultUIService.showDialog(DefaultUIService.java:304)
-> at org.scijava.ui.DefaultUIService.showDialog(DefaultUIService.java:304)
```

**Comment by mdoube** [comment]
Now it's passing completely on laptop. Closing as unreproducible.
