### ISSUE TITLE
Intertrabecular Angles Wrapper fails in Headless mode 

### ISSUE THREAD

**Issue by harshamarupudi56** [bonej-org/BoneJ2#317]
I am attempting to run the intertrabecular angles plugin in headless mode. The image I am running this on is shrew.tif Which can be found at the bottom of this page. 

https://bonej.org/ef

I have enclosed the script I am using below to run the wrapper with comments. 

```
# @CommandService cs  
# @TableIOService tios

from ij import IJ
from ij import ImagePlus
from org.scijava.table.io import TableIOOptions
from org.bonej.utilities import SharedTable as table
 
#Set data input-output paths 
input_dir = "/projects/"
input_image_path = input_dir+"shrew.tif"
outputdir = "/measurements/"

#clear old results from the table
IJ.run("Clear BoneJ results");
 
#open input image as IJ1-style ImagePlus to be compatible with wrapper  
inputImagePlus = IJ.openImage(input_image_path)
#inputImagePlus.show()

#Run Intertrabecular Angles Plugin specifying parameters 

wrapper = cs.run("org.bonej.wrapperPlugins.IntertrabecularAngleWrapper", False, ["inputImage",inputImagePlus, "minimumValence", 3, "maximumValence", 50, "minimumTrabecularLength", 0, "marginCutOff", 10, "iteratePruning", True, "useClusters", True, "printCentroids", True,"printCulledEdgePercentages", False, "showSkeleton", True])

#must call wrapper.get() to populate the result table with data
wrapperInstance = wrapper.get()

#Get and save the skeleton image. Here, you don't have to specify the name of the output.
skeleton= wrapperInstance.getOutput("")
IJ.save(skeleton, outputdir+"skeleton.tif")

#save the result table
tios.save(table.getTable(), outputdir+"ITA.csv", TableIOOptions())
```

This script works when wrapper = cs.run("org.bonej.wrapperPlugins.InterTravbecularAngleWrapper", is set to True. This runs the plugin with the GUI and has no issues. When it is set in False to run headlessly I find that the script will generate the skeleton image and then proceed to fail. I have included the error message below. The code fails on wrapperInstance = wrapper.get(). The initial issue I was having was that a dialog box was popping up to confirm the largest skeleton was being processed. I could not click ok in headless mode which resulted in failure. Since then Michael has removed this yet there is still a failure in the code. 

```
File "New_.py", line 28, in <module>
> 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
> 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
> 
> 	at org.python.core.Py.JavaError(Py.java:547)
> 	at org.python.core.Py.JavaError(Py.java:538)
> 	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:192)
> 	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:208)
> 	at org.python.core.PyObject.__call__(PyObject.java:461)
> 	at org.python.core.PyObject.__call__(PyObject.java:465)
> 	at org.python.core.PyMethod.__call__(PyMethod.java:126)
> 	at org.python.pycode._pyx11.f$0(New_.py:35)
> 	at org.python.pycode._pyx11.call_function(New_.py)
> 	at org.python.core.PyTableCode.call(PyTableCode.java:173)
> 	at org.python.core.PyCode.call(PyCode.java:18)
> 	at org.python.core.Py.runCode(Py.java:1687)
> 	at org.python.core.__builtin__.eval(__builtin__.java:497)
> 	at org.python.core.__builtin__.eval(__builtin__.java:501)
> 	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:255)
> 	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
> 	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
> 	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
> 	at org.scijava.script.ScriptModule.run(ScriptModule.java:157)
> 	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
> 	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
> 	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
> 	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
> 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
> 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:190)
> 	... 24 more
> Caused by: java.lang.RuntimeException: Module threw exception
> 	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
> 	... 6 more
> Caused by: java.lang.NullPointerException
> 	at sc.fiji.analyzeSkeleton.ita.GraphPruning.length(GraphPruning.java:458)
> 	at sc.fiji.analyzeSkeleton.ita.GraphPruning.euclideanDistance(GraphPruning.java:339)
> 	at sc.fiji.analyzeSkeleton.ita.GraphPruning.lambda$pruneShortEdges$0(GraphPruning.java:155)
> 	at java.util.ArrayList.forEach(ArrayList.java:1257)
> 	at sc.fiji.analyzeSkeleton.ita.GraphPruning.pruneShortEdges(GraphPruning.java:155)
> 	at org.bonej.wrapperPlugins.IntertrabecularAngleWrapper.run(IntertrabecularAngleWrapper.java:216)
> 	at org.scijava.command.CommandModule.run(CommandModule.java:196)
> 	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
> 	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
> 	... 6 more
```

**Comment by mdoube** [comment]
Thanks for the report. How do you execute the script? Please be explicit including details of the environment, OS, Fiji and Java and Python versions etc., and any arguments that you pass when running it.

In the meantime you could try [building a development branch](https://github.com/bonej-org/BoneJ2/wiki/How-to-try-out-development-code), linked below, of your own that *might* fix this behaviour.

https://github.com/bonej-org/BoneJ2/tree/ita-calibration

**Comment by mdoube** [comment]
> This script works when wrapper = cs.run("org.bonej.wrapperPlugins.InterTravbecularAngleWrapper", is set to True. This runs the plugin with the GUI and has no issues. When it is set in False to run headlessly I find that the script will generate the skeleton image and then proceed to fail

I am not sure that the second argument is meant as a flag to run headless. The [Javadoc](url) rather states:

> process - If true, executes the command with pre- and postprocessing steps from all available [PreprocessorPlugin](https://javadoc.scijava.org/SciJava/org/scijava/module/process/PreprocessorPlugin.html)s and [PostprocessorPlugin](https://javadoc.scijava.org/SciJava/org/scijava/module/process/PostprocessorPlugin.html)s in the plugin index; if false, executes the command with no pre- or postprocessing. For more fine-grained control, see the [ModuleService.run(org.scijava.module.ModuleInfo, boolean, java.lang.Object...)](https://javadoc.scijava.org/SciJava/org/scijava/module/ModuleService.html#run-org.scijava.module.ModuleInfo-boolean-java.lang.Object...-) methods.

I think what is happening is that there is a `NullPointerException` caused by an uninitialised instance variable, which for reasons I don't fully understand, occurs only when called from a script as you have here.

```
> Caused by: java.lang.NullPointerException
> 	at sc.fiji.analyzeSkeleton.ita.GraphPruning.length(GraphPruning.java:458)
```
[This commit](https://github.com/bonej-org/BoneJ2/commit/761b3ca4b7255e397eeb56544ee4353afbdafea0) should fix it.

**Comment by harshamarupudi56** [comment]
I am using Fiji version v1.53r, Java version 1.80_172, and Python version 3.97. All of this is being run on Linux/Ubutnu. The script is identical to what you had shared with me on the forums with only the filepaths altered. I see there is a commit for the Intertrabecular angles wrapper but I didn't see that there was an update for BoneJ.

**Comment by mdoube** [comment]
> The script is identical to what you had shared with me on the forums with only the filepaths altered.

Do you execute it from the ImageJ script editor or from the command line (or another environment) and if so, how precisely do you run it?

>  I see there is a commit for the Intertrabecular angles wrapper but I didn't see that there was an update for BoneJ.

The commit is still on a development branch and has not yet been merged to master. To test it you will need to [follow the instructions](https://github.com/bonej-org/BoneJ2/wiki/How-to-try-out-development-code) to build a development version of this branch:

https://github.com/bonej-org/BoneJ2/tree/ita-calibration

**Comment by harshamarupudi56** [comment]
Sorry for the late reply. I had trouble with using git and wasn't able to build a development version of this branch.
